In [3]:
import pandas as pd

In [89]:
df_cms = pd.read_csv('2014-2023 Medicare Fee-for-Service Geographic Variation Public Use File.csv')

/var/folders/nb/twl23ck96hx2_y5hrqk4zg8m0000gn/T/ipykernel_28384/3495723731.py:1: DtypeWarning: Columns (223,224) have mixed types. Specify dtype option on import or set low_memory=False.
  df_cms = pd.read_csv('2014-2023 Medicare Fee-for-Service Geographic Variation Public Use File.csv')

In [90]:
df_cms_clean = df_cms.replace('*', pd.NA)

In [9]:
df_cms_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33639 entries, 0 to 33638
Columns: 247 entries, YEAR to PQI16_LWRXTRMTY_AMPUTN_AGE_GE_75
dtypes: float64(1), int64(1), object(245)
memory usage: 63.4+ MB

In [93]:
print(df_cms_clean.columns)

Index(['YEAR', 'BENE_GEO_LVL', 'BENE_GEO_DESC', 'BENE_GEO_CD', 'BENE_AGE_LVL',
       'BENES_TOTAL_CNT', 'BENES_WTH_PTAPTB_CNT', 'BENES_FFS_CNT',
       'BENES_MA_CNT', 'MA_PRTCPTN_RATE',
       ...
       'PQI11_BCTRL_PNA_AGE_LT_65', 'PQI11_BCTRL_PNA_AGE_65_74',
       'PQI11_BCTRL_PNA_AGE_GE_75', 'PQI12_UTI_AGE_LT_65',
       'PQI12_UTI_AGE_65_74', 'PQI12_UTI_AGE_GE_75', 'PQI15_ASTHMA_AGE_LT_40',
       'PQI16_LWRXTRMTY_AMPUTN_AGE_LT_65', 'PQI16_LWRXTRMTY_AMPUTN_AGE_65_74',
       'PQI16_LWRXTRMTY_AMPUTN_AGE_GE_75'],
      dtype='object', length=247)

In [95]:
df_demographics = df_cms_clean[['YEAR', 'BENE_GEO_LVL', 'BENE_GEO_DESC', 'BENE_AGE_LVL', 'BENES_TOTAL_CNT', 'BENES_WTH_PTAPTB_CNT', 'BENES_FFS_CNT', 'BENES_MA_CNT', 'MA_PRTCPTN_RATE', 'BENE_AVG_AGE', 'BENE_FEML_PCT', 'BENE_MALE_PCT', 'BENE_RACE_WHT_PCT', 'BENE_RACE_BLACK_PCT', 'BENE_RACE_HSPNC_PCT', 'BENE_RACE_OTHR_PCT', 'BENE_DUAL_PCT', 'BENE_AVG_RISK_SCRE']]

In [151]:
df_demographics.loc[:, 'BENE_FEML_PCT'] = pd.to_numeric(df_demographics['BENE_FEML_PCT'], errors='coerce')
df_demographics.loc[:, 'BENE_MALE_PCT'] = pd.to_numeric(df_demographics['BENE_MALE_PCT'], errors='coerce')
df_demographics.loc[:, 'BENE_RACE_WHT_PCT'] = pd.to_numeric(df_demographics['BENE_RACE_WHT_PCT'], errors='coerce')
df_demographics.loc[:, 'BENE_RACE_BLACK_PCT'] = pd.to_numeric(df_demographics['BENE_RACE_BLACK_PCT'], errors='coerce')
df_demographics.loc[:, 'BENE_RACE_HSPNC_PCT'] = pd.to_numeric(df_demographics['BENE_RACE_HSPNC_PCT'], errors='coerce')
df_demographics.loc[:, 'BENE_RACE_OTHR_PCT'] = pd.to_numeric(df_demographics['BENE_RACE_OTHR_PCT'], errors='coerce')
df_demographics.loc[:, 'BENE_DUAL_PCT'] = pd.to_numeric(df_demographics['BENE_DUAL_PCT'], errors='coerce')
df_demographics.loc[:, 'BENE_AVG_RISK_SCRE'] = pd.to_numeric(df_demographics['BENE_AVG_RISK_SCRE'], errors='coerce')

In [153]:
df_demographics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33639 entries, 0 to 33638
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   YEAR                  33639 non-null  int64
 1   BENE_GEO_LVL          33639 non-null  object
 2   BENE_GEO_DESC         33609 non-null  object
 3   BENE_AGE_LVL          33639 non-null  object
 4   BENES_TOTAL_CNT       33062 non-null  object
 5   BENES_WTH_PTAPTB_CNT  32474 non-null  object
 6   BENES_FFS_CNT         33059 non-null  object
 7   BENES_MA_CNT          32474 non-null  object
 8   MA_PRTCPTN_RATE       32474 non-null  object
 9   BENE_AVG_AGE          33059 non-null  object
 10  BENE_FEML_PCT         33043 non-null  float64
 11  BENE_MALE_PCT         33043 non-null  float64
 12  BENE_RACE_WHT_PCT     20561 non-null  float64
 13  BENE_RACE_BLACK_PCT   20561 non-null  float64
 14  BENE_RACE_HSPNC_PCT   20561 non-null  float64
 15  BENE_RACE_OTHR_PCT    20561 non-null  float64
 16  BENE_DUAL_PCT         32830 non-null  float64
 17  BENE_AVG_RISK_SCRE    33059 non-null  float64
dtypes: float64(8), int64(1), object(9)
memory usage: 4.6+ MB

In [155]:
missing_rows = df_demographics.isna().sum(axis=1)

In [157]:
missing_rows[missing_rows > 0]

6         7
7         4
9         7
11        4
12        7
         ..
33633     4
33635     4
33636    15
33637    15
33638    15
Length: 13197, dtype: int64

In [159]:
missing_rows_count = df_demographics.isna().any(axis=1).sum()
print(f"Total rows with missing values: {missing_rows_count}")

Total rows with missing values: 13197

In [163]:
missing_values_per_column = df_demographics.isna().sum()
print(missing_values_per_column[missing_values_per_column > 0])

BENE_GEO_DESC              30
BENES_TOTAL_CNT           577
BENES_WTH_PTAPTB_CNT     1165
BENES_FFS_CNT             580
BENES_MA_CNT             1165
MA_PRTCPTN_RATE          1165
BENE_AVG_AGE              580
BENE_FEML_PCT             596
BENE_MALE_PCT             596
BENE_RACE_WHT_PCT       13078
BENE_RACE_BLACK_PCT     13078
BENE_RACE_HSPNC_PCT     13078
BENE_RACE_OTHR_PCT      13078
BENE_DUAL_PCT             809
BENE_AVG_RISK_SCRE        580
dtype: int64

In [165]:
df_demographics_cleaned = df_demographics.dropna()
print(df_demographics_cleaned.info())

<class 'pandas.core.frame.DataFrame'>
Index: 20442 entries, 0 to 33634
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   YEAR                  20442 non-null  int64
 1   BENE_GEO_LVL          20442 non-null  object
 2   BENE_GEO_DESC         20442 non-null  object
 3   BENE_AGE_LVL          20442 non-null  object
 4   BENES_TOTAL_CNT       20442 non-null  object
 5   BENES_WTH_PTAPTB_CNT  20442 non-null  object
 6   BENES_FFS_CNT         20442 non-null  object
 7   BENES_MA_CNT          20442 non-null  object
 8   MA_PRTCPTN_RATE       20442 non-null  object
 9   BENE_AVG_AGE          20442 non-null  object
 10  BENE_FEML_PCT         20442 non-null  float64
 11  BENE_MALE_PCT         20442 non-null  float64
 12  BENE_RACE_WHT_PCT     20442 non-null  float64
 13  BENE_RACE_BLACK_PCT   20442 non-null  float64
 14  BENE_RACE_HSPNC_PCT   20442 non-null  float64
 15  BENE_RACE_OTHR_PCT    20442 non-null  float64
 16  BENE_DUAL_PCT         20442 non-null  float64
 17  BENE_AVG_RISK_SCRE    20442 non-null  float64
dtypes: float64(8), int64(1), object(9)
memory usage: 3.0+ MB
None

In [167]:
missing_values_per_column = df_demographics.isna().sum()
print(missing_values_per_column[missing_values_per_column > 0])

BENE_GEO_DESC              30
BENES_TOTAL_CNT           577
BENES_WTH_PTAPTB_CNT     1165
BENES_FFS_CNT             580
BENES_MA_CNT             1165
MA_PRTCPTN_RATE          1165
BENE_AVG_AGE              580
BENE_FEML_PCT             596
BENE_MALE_PCT             596
BENE_RACE_WHT_PCT       13078
BENE_RACE_BLACK_PCT     13078
BENE_RACE_HSPNC_PCT     13078
BENE_RACE_OTHR_PCT      13078
BENE_DUAL_PCT             809
BENE_AVG_RISK_SCRE        580
dtype: int64

In [169]:
display(df_demographics)

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_AGE_LVL,BENES_TOTAL_CNT,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_MA_CNT,MA_PRTCPTN_RATE,BENE_AVG_AGE,BENE_FEML_PCT,BENE_MALE_PCT,BENE_RACE_WHT_PCT,BENE_RACE_BLACK_PCT,BENE_RACE_HSPNC_PCT,BENE_RACE_OTHR_PCT,BENE_DUAL_PCT,BENE_AVG_RISK_SCRE
0,2014,National,National,All,56767775,49302821,33462969,15839852,0.3213,71,0.5505,0.4495,0.7993,0.0971,0.0584,0.0452,0.2148,1.00
1,2014,National,National,<65,9286837,7824336,5867170,1957166,0.2501,51,0.4769,0.5231,0.6725,0.1978,0.0885,0.0412,0.5736,1.14
2,2014,National,National,>=65,47480938,41478485,27595799,13882686,0.3347,76,0.5661,0.4339,0.8263,0.0757,0.0520,0.0461,0.1385,0.97
3,2014,State,AK,All,84573,71860,71383,477,0.0066,70,0.5032,0.4968,0.7443,0.0264,0.0247,0.2047,0.2381,0.81
4,2014,State,AK,<65,13294,11641,11578,63,0.0054,51,0.4604,0.5396,0.6263,0.0596,0.0342,0.2799,0.6498,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33634,2023,County,WY-Washakie,All,2209,1949,1651,298,0.1529,74,0.5106,0.4894,0.9098,0.0000,0.0648,0.0254,0.1096,0.76
33635,2023,County,WY-Weston,All,1915,1699,1451,248,0.146,73,0.5031,0.4969,NaN,NaN,NaN,NaN,0.0910,0.75
33636,2023,State,<NA>,All,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33637,2023,State,<NA>,<65,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33638,2023,State,<NA>,>=65,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [195]:
df_demographics = df_demographics.replace('ZZ', pd.NA)

In [173]:
display(df_demographics)

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_AGE_LVL,BENES_TOTAL_CNT,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_MA_CNT,MA_PRTCPTN_RATE,BENE_AVG_AGE,BENE_FEML_PCT,BENE_MALE_PCT,BENE_RACE_WHT_PCT,BENE_RACE_BLACK_PCT,BENE_RACE_HSPNC_PCT,BENE_RACE_OTHR_PCT,BENE_DUAL_PCT,BENE_AVG_RISK_SCRE
0,2014,National,National,All,56767775,49302821,33462969,15839852,0.3213,71,0.5505,0.4495,0.7993,0.0971,0.0584,0.0452,0.2148,1.00
1,2014,National,National,<65,9286837,7824336,5867170,1957166,0.2501,51,0.4769,0.5231,0.6725,0.1978,0.0885,0.0412,0.5736,1.14
2,2014,National,National,>=65,47480938,41478485,27595799,13882686,0.3347,76,0.5661,0.4339,0.8263,0.0757,0.0520,0.0461,0.1385,0.97
3,2014,State,AK,All,84573,71860,71383,477,0.0066,70,0.5032,0.4968,0.7443,0.0264,0.0247,0.2047,0.2381,0.81
4,2014,State,AK,<65,13294,11641,11578,63,0.0054,51,0.4604,0.5396,0.6263,0.0596,0.0342,0.2799,0.6498,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33634,2023,County,WY-Washakie,All,2209,1949,1651,298,0.1529,74,0.5106,0.4894,0.9098,0.0000,0.0648,0.0254,0.1096,0.76
33635,2023,County,WY-Weston,All,1915,1699,1451,248,0.146,73,0.5031,0.4969,NaN,NaN,NaN,NaN,0.0910,0.75
33636,2023,State,<NA>,All,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33637,2023,State,<NA>,<65,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33638,2023,State,<NA>,>=65,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [197]:
df_demographics_clean = df_demographics.dropna()
display(df_demographics_clean)

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_AGE_LVL,BENES_TOTAL_CNT,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_MA_CNT,MA_PRTCPTN_RATE,BENE_AVG_AGE,BENE_FEML_PCT,BENE_MALE_PCT,BENE_RACE_WHT_PCT,BENE_RACE_BLACK_PCT,BENE_RACE_HSPNC_PCT,BENE_RACE_OTHR_PCT,BENE_DUAL_PCT,BENE_AVG_RISK_SCRE
0,2014,National,National,All,56767775,49302821,33462969,15839852,0.3213,71,0.5505,0.4495,0.7993,0.0971,0.0584,0.0452,0.2148,1.00
1,2014,National,National,<65,9286837,7824336,5867170,1957166,0.2501,51,0.4769,0.5231,0.6725,0.1978,0.0885,0.0412,0.5736,1.14
2,2014,National,National,>=65,47480938,41478485,27595799,13882686,0.3347,76,0.5661,0.4339,0.8263,0.0757,0.0520,0.0461,0.1385,0.97
3,2014,State,AK,All,84573,71860,71383,477,0.0066,70,0.5032,0.4968,0.7443,0.0264,0.0247,0.2047,0.2381,0.81
4,2014,State,AK,<65,13294,11641,11578,63,0.0054,51,0.4604,0.5396,0.6263,0.0596,0.0342,0.2799,0.6498,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33622,2023,County,WY-Laramie,All,21839,18972,15544,3428,0.1807,73,0.5413,0.4587,0.8696,0.0140,0.0685,0.0479,0.1122,0.86
33624,2023,County,WY-Natrona,All,16932,14938,12828,2110,0.1413,72,0.5289,0.4711,0.9247,0.0057,0.0321,0.0375,0.1240,0.85
33628,2023,County,WY-Sheridan,All,8829,7885,7172,713,0.0904,73,0.5265,0.4735,0.9403,0.0021,0.0141,0.0435,0.0839,0.73
33630,2023,County,WY-Sweetwater,All,7606,6795,6234,561,0.0826,71,0.5168,0.4832,0.8744,0.0061,0.0841,0.0355,0.1116,0.79
33634,2023,County,WY-Washakie,All,2209,1949,1651,298,0.1529,74,0.5106,0.4894,0.9098,0.0000,0.0648,0.0254,0.1096,0.76

In [177]:
print(df_demographics_clean.info())

<class 'pandas.core.frame.DataFrame'>
Index: 20442 entries, 0 to 33634
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   YEAR                  20442 non-null  int64
 1   BENE_GEO_LVL          20442 non-null  object
 2   BENE_GEO_DESC         20442 non-null  object
 3   BENE_AGE_LVL          20442 non-null  object
 4   BENES_TOTAL_CNT       20442 non-null  object
 5   BENES_WTH_PTAPTB_CNT  20442 non-null  object
 6   BENES_FFS_CNT         20442 non-null  object
 7   BENES_MA_CNT          20442 non-null  object
 8   MA_PRTCPTN_RATE       20442 non-null  object
 9   BENE_AVG_AGE          20442 non-null  object
 10  BENE_FEML_PCT         20442 non-null  float64
 11  BENE_MALE_PCT         20442 non-null  float64
 12  BENE_RACE_WHT_PCT     20442 non-null  float64
 13  BENE_RACE_BLACK_PCT   20442 non-null  float64
 14  BENE_RACE_HSPNC_PCT   20442 non-null  float64
 15  BENE_RACE_OTHR_PCT    20442 non-null  float64
 16  BENE_DUAL_PCT         20442 non-null  float64
 17  BENE_AVG_RISK_SCRE    20442 non-null  float64
dtypes: float64(8), int64(1), object(9)
memory usage: 3.0+ MB
None

In [87]:
display(df_demographics_clean)

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_AGE_LVL,BENES_TOTAL_CNT,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_MA_CNT,MA_PRTCPTN_RATE,BENE_AVG_AGE,BENE_FEML_PCT,BENE_MALE_PCT,BENE_RACE_WHT_PCT,BENE_RACE_BLACK_PCT,BENE_RACE_HSPNC_PCT,BENE_RACE_OTHR_PCT,BENE_DUAL_PCT,BENE_AVG_RISK_SCRE
0,2014,National,National,All,56767775,49302821,33462969,15839852,0.3213,71,0.5505,0.4495,0.7993,0.0971,0.0584,0.0452,0.2148,1.00
1,2014,National,National,<65,9286837,7824336,5867170,1957166,0.2501,51,0.4769,0.5231,0.6725,0.1978,0.0885,0.0412,0.5736,1.14
2,2014,National,National,>=65,47480938,41478485,27595799,13882686,0.3347,76,0.5661,0.4339,0.8263,0.0757,0.0520,0.0461,0.1385,0.97
3,2014,State,AK,All,84573,71860,71383,477,0.0066,70,0.5032,0.4968,0.7443,0.0264,0.0247,0.2047,0.2381,0.81
4,2014,State,AK,<65,13294,11641,11578,63,0.0054,51,0.4604,0.5396,0.6263,0.0596,0.0342,0.2799,0.6498,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33622,2023,County,WY-Laramie,All,21839,18972,15544,3428,0.1807,73,0.5413,0.4587,0.8696,0.0140,0.0685,0.0479,0.1122,0.86
33624,2023,County,WY-Natrona,All,16932,14938,12828,2110,0.1413,72,0.5289,0.4711,0.9247,0.0057,0.0321,0.0375,0.1240,0.85
33628,2023,County,WY-Sheridan,All,8829,7885,7172,713,0.0904,73,0.5265,0.4735,0.9403,0.0021,0.0141,0.0435,0.0839,0.73
33630,2023,County,WY-Sweetwater,All,7606,6795,6234,561,0.0826,71,0.5168,0.4832,0.8744,0.0061,0.0841,0.0355,0.1116,0.79
33634,2023,County,WY-Washakie,All,2209,1949,1651,298,0.1529,74,0.5106,0.4894,0.9098,0.0000,0.0648,0.0254,0.1096,0.76

In [123]:
df_demographics_clean.columns

Index(['YEAR', 'BENE_GEO_LVL', 'BENE_GEO_DESC', 'BENE_AGE_LVL',
       'BENES_TOTAL_CNT', 'BENES_WTH_PTAPTB_CNT', 'BENES_FFS_CNT',
       'BENES_MA_CNT', 'MA_PRTCPTN_RATE', 'BENE_AVG_AGE', 'BENE_FEML_PCT',
       'BENE_MALE_PCT', 'BENE_RACE_WHT_PCT', 'BENE_RACE_BLACK_PCT',
       'BENE_RACE_HSPNC_PCT', 'BENE_RACE_OTHR_PCT', 'BENE_DUAL_PCT',
       'BENE_AVG_RISK_SCRE'],
      dtype='object')

In [199]:
numeric_columns = [
    'BENES_TOTAL_CNT', 'BENES_WTH_PTAPTB_CNT', 'BENES_FFS_CNT', 'BENES_MA_CNT', 
    'MA_PRTCPTN_RATE', 'BENE_AVG_AGE', 'BENE_FEML_PCT', 'BENE_MALE_PCT',
    'BENE_RACE_WHT_PCT', 'BENE_RACE_BLACK_PCT', 'BENE_RACE_HSPNC_PCT', 
    'BENE_RACE_OTHR_PCT', 'BENE_DUAL_PCT', 'BENE_AVG_RISK_SCRE'
]
for column in numeric_columns:
    df_demographics_clean[column] = pd.to_numeric(df_demographics_clean[column], errors='coerce')
non_numeric_columns = df_demographics_clean.select_dtypes(exclude=['number']).columns
print("Non-numeric columns after conversion:", non_numeric_columns)

/var/folders/nb/twl23ck96hx2_y5hrqk4zg8m0000gn/T/ipykernel_28384/1860658685.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_demographics_clean[column] = pd.to_numeric(df_demographics_clean[column], errors='coerce')

Non-numeric columns after conversion: Index(['BENE_GEO_LVL', 'BENE_GEO_DESC', 'BENE_AGE_LVL'], dtype='object')

In [201]:
df_demographics_clean.head()

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_AGE_LVL,BENES_TOTAL_CNT,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_MA_CNT,MA_PRTCPTN_RATE,BENE_AVG_AGE,BENE_FEML_PCT,BENE_MALE_PCT,BENE_RACE_WHT_PCT,BENE_RACE_BLACK_PCT,BENE_RACE_HSPNC_PCT,BENE_RACE_OTHR_PCT,BENE_DUAL_PCT,BENE_AVG_RISK_SCRE
0,2014,National,National,All,56767775,49302821,33462969,15839852,0.3213,71,0.5505,0.4495,0.7993,0.0971,0.0584,0.0452,0.2148,1.00
1,2014,National,National,<65,9286837,7824336,5867170,1957166,0.2501,51,0.4769,0.5231,0.6725,0.1978,0.0885,0.0412,0.5736,1.14
2,2014,National,National,>=65,47480938,41478485,27595799,13882686,0.3347,76,0.5661,0.4339,0.8263,0.0757,0.0520,0.0461,0.1385,0.97
3,2014,State,AK,All,84573,71860,71383,477,0.0066,70,0.5032,0.4968,0.7443,0.0264,0.0247,0.2047,0.2381,0.81
4,2014,State,AK,<65,13294,11641,11578,63,0.0054,51,0.4604,0.5396,0.6263,0.0596,0.0342,0.2799,0.6498,1.01

In [139]:
display(df_demographics_clean)

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_AGE_LVL,BENES_TOTAL_CNT,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_MA_CNT,MA_PRTCPTN_RATE,BENE_AVG_AGE,BENE_FEML_PCT,BENE_MALE_PCT,BENE_RACE_WHT_PCT,BENE_RACE_BLACK_PCT,BENE_RACE_HSPNC_PCT,BENE_RACE_OTHR_PCT,BENE_DUAL_PCT,BENE_AVG_RISK_SCRE
0,2014,National,National,All,56767775,49302821,33462969,15839852,0.3213,71,0.5505,0.4495,0.7993,0.0971,0.0584,0.0452,0.2148,1.00
1,2014,National,National,<65,9286837,7824336,5867170,1957166,0.2501,51,0.4769,0.5231,0.6725,0.1978,0.0885,0.0412,0.5736,1.14
2,2014,National,National,>=65,47480938,41478485,27595799,13882686,0.3347,76,0.5661,0.4339,0.8263,0.0757,0.0520,0.0461,0.1385,0.97
3,2014,State,AK,All,84573,71860,71383,477,0.0066,70,0.5032,0.4968,0.7443,0.0264,0.0247,0.2047,0.2381,0.81
4,2014,State,AK,<65,13294,11641,11578,63,0.0054,51,0.4604,0.5396,0.6263,0.0596,0.0342,0.2799,0.6498,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33622,2023,County,WY-Laramie,All,21839,18972,15544,3428,0.1807,73,0.5413,0.4587,0.8696,0.0140,0.0685,0.0479,0.1122,0.86
33624,2023,County,WY-Natrona,All,16932,14938,12828,2110,0.1413,72,0.5289,0.4711,0.9247,0.0057,0.0321,0.0375,0.1240,0.85
33628,2023,County,WY-Sheridan,All,8829,7885,7172,713,0.0904,73,0.5265,0.4735,0.9403,0.0021,0.0141,0.0435,0.0839,0.73
33630,2023,County,WY-Sweetwater,All,7606,6795,6234,561,0.0826,71,0.5168,0.4832,0.8744,0.0061,0.0841,0.0355,0.1116,0.79
33634,2023,County,WY-Washakie,All,2209,1949,1651,298,0.1529,74,0.5106,0.4894,0.9098,0.0000,0.0648,0.0254,0.1096,0.76

In [261]:
df_demographics_clean.rename(columns={
    'BENE_GEO_DESC': 'State/County',  
    'BENE_GEO_LVL': 'Geographical Level',
    'BENE_AGE_LVL': 'Age Level',
    'BENE_FEML_PCT': 'Female Percentage',
    'BENE_MALE_PCT': 'Male Percentage',
    'BENE_RACE_WHT_PCT': 'White Percentage',
    'BENE_RACE_BLACK_PCT': 'Black Percentage',
    'BENE_RACE_HSPNC_PCT': 'Hispanic Percentage',
    'BENE_RACE_OTHR_PCT': 'Other Race Percentage',
    'BENE_DUAL_PCT': 'Dual Eligibility Percentage',
    'BENE_AVG_RISK_SCRE': 'Average HCC Risk Score',
    'BENES_TOTAL_CNT': 'Total Beneficiaries Count',
    'BENES_WTH_PTAPTB_CNT': 'Part A and B Beneficiaries Count',
    'BENES_FFS_CNT': 'Fee-For-Service Beneficiaries Count',
    'BENES_MA_CNT': 'Medicare Advantage Beneficiaries Count',
    'MA_PRTCPTN_RATE': 'Medicare Advantage Participation Rate',
    'BENE_AVG_AGE': 'Average Beneficiary Age'
}, inplace=True)

/var/folders/nb/twl23ck96hx2_y5hrqk4zg8m0000gn/T/ipykernel_28384/1626388413.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_demographics_clean.rename(columns={

In [263]:
display(df_demographics_clean)

,YEAR,Geographical Level,State/County,Age Level,Total Beneficiaries Count,Part A and B Beneficiaries Count,Fee-For-Service Beneficiaries Count,Medicare Advantage Beneficiaries Count,Medicare Advantage Participation Rate,Average Beneficiary Age,Female Percentage,Male Percentage,White Percentage,Black Percentage,Hispanic Percentage,Other Race Percentage,Dual Eligibility Percentage,Average Risk Score
0,2014,National,National,All,56767775,49302821,33462969,15839852,0.3213,71,0.5505,0.4495,0.7993,0.0971,0.0584,0.0452,0.2148,1.00
1,2014,National,National,<65,9286837,7824336,5867170,1957166,0.2501,51,0.4769,0.5231,0.6725,0.1978,0.0885,0.0412,0.5736,1.14
2,2014,National,National,>=65,47480938,41478485,27595799,13882686,0.3347,76,0.5661,0.4339,0.8263,0.0757,0.0520,0.0461,0.1385,0.97
3,2014,State,AK,All,84573,71860,71383,477,0.0066,70,0.5032,0.4968,0.7443,0.0264,0.0247,0.2047,0.2381,0.81
4,2014,State,AK,<65,13294,11641,11578,63,0.0054,51,0.4604,0.5396,0.6263,0.0596,0.0342,0.2799,0.6498,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33622,2023,County,WY-Laramie,All,21839,18972,15544,3428,0.1807,73,0.5413,0.4587,0.8696,0.0140,0.0685,0.0479,0.1122,0.86
33624,2023,County,WY-Natrona,All,16932,14938,12828,2110,0.1413,72,0.5289,0.4711,0.9247,0.0057,0.0321,0.0375,0.1240,0.85
33628,2023,County,WY-Sheridan,All,8829,7885,7172,713,0.0904,73,0.5265,0.4735,0.9403,0.0021,0.0141,0.0435,0.0839,0.73
33630,2023,County,WY-Sweetwater,All,7606,6795,6234,561,0.0826,71,0.5168,0.4832,0.8744,0.0061,0.0841,0.0355,0.1116,0.79
33634,2023,County,WY-Washakie,All,2209,1949,1651,298,0.1529,74,0.5106,0.4894,0.9098,0.0000,0.0648,0.0254,0.1096,0.76

In [265]:
df_demographics_clean.to_csv('cms_demographics.csv', index=False)