In [125]:
import pandas as pd

In [127]:
df_payment_models = pd.read_csv('2014-2023 Medicare Fee-for-Service Geographic Variation Public Use File.csv')

/var/folders/nb/twl23ck96hx2_y5hrqk4zg8m0000gn/T/ipykernel_4701/2726900944.py:1: DtypeWarning: Columns (223,224) have mixed types. Specify dtype option on import or set low_memory=False.
  df_payment_models = pd.read_csv('2014-2023 Medicare Fee-for-Service Geographic Variation Public Use File.csv')

In [128]:
df_payment_models.columns

Index(['YEAR', 'BENE_GEO_LVL', 'BENE_GEO_DESC', 'BENE_GEO_CD', 'BENE_AGE_LVL',
       'BENES_TOTAL_CNT', 'BENES_WTH_PTAPTB_CNT', 'BENES_FFS_CNT',
       'BENES_MA_CNT', 'MA_PRTCPTN_RATE',
       ...
       'PQI11_BCTRL_PNA_AGE_LT_65', 'PQI11_BCTRL_PNA_AGE_65_74',
       'PQI11_BCTRL_PNA_AGE_GE_75', 'PQI12_UTI_AGE_LT_65',
       'PQI12_UTI_AGE_65_74', 'PQI12_UTI_AGE_GE_75', 'PQI15_ASTHMA_AGE_LT_40',
       'PQI16_LWRXTRMTY_AMPUTN_AGE_LT_65', 'PQI16_LWRXTRMTY_AMPUTN_AGE_65_74',
       'PQI16_LWRXTRMTY_AMPUTN_AGE_GE_75'],
      dtype='object', length=247)

In [131]:
display(df_payment_models)

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_GEO_CD,BENE_AGE_LVL,BENES_TOTAL_CNT,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_MA_CNT,MA_PRTCPTN_RATE,...,PQI11_BCTRL_PNA_AGE_LT_65,PQI11_BCTRL_PNA_AGE_65_74,PQI11_BCTRL_PNA_AGE_GE_75,PQI12_UTI_AGE_LT_65,PQI12_UTI_AGE_65_74,PQI12_UTI_AGE_GE_75,PQI15_ASTHMA_AGE_LT_40,PQI16_LWRXTRMTY_AMPUTN_AGE_LT_65,PQI16_LWRXTRMTY_AMPUTN_AGE_65_74,PQI16_LWRXTRMTY_AMPUTN_AGE_GE_75
0,2014,National,National,NaN,All,56767775,49302821,33462969,15839852,0.3213,...,686,499,1373,361,269,1120,286,147,50,47
1,2014,National,National,NaN,<65,9286837,7824336,5867170,1957166,0.2501,...,686,NaN,NaN,361,NaN,NaN,286,147,NaN,NaN
2,2014,National,National,NaN,>=65,47480938,41478485,27595799,13882686,0.3347,...,NaN,499,1373,NaN,269,1120,NaN,NaN,50,47
3,2014,State,AK,2.0,All,84573,71860,71383,477,0.0066,...,622,366,1271,181,152,703,*,130,*,72
4,2014,State,AK,2.0,<65,13294,11641,11578,63,0.0054,...,622,NaN,NaN,181,NaN,NaN,*,130,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33634,2023,County,WY-Washakie,56043.0,All,2209,1949,1651,298,0.1529,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33635,2023,County,WY-Weston,56045.0,All,1915,1699,1451,248,0.146,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33636,2023,State,ZZ,NaN,All,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
33637,2023,State,ZZ,NaN,<65,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
33638,2023,State,ZZ,NaN,>=65,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*

In [133]:
df_pm_cleaned = df_payment_models.replace('*', pd.NA)

In [135]:
missing_values = df_pm_cleaned.isna().sum()
missing_values[missing_values > 0]

BENE_GEO_CD                           120
BENES_TOTAL_CNT                       577
BENES_WTH_PTAPTB_CNT                 1165
BENES_FFS_CNT                         580
BENES_MA_CNT                         1165
                                    ...
PQI12_UTI_AGE_GE_75                 32505
PQI15_ASTHMA_AGE_LT_40              32901
PQI16_LWRXTRMTY_AMPUTN_AGE_LT_65    32537
PQI16_LWRXTRMTY_AMPUTN_AGE_65_74    32527
PQI16_LWRXTRMTY_AMPUTN_AGE_GE_75    32537
Length: 243, dtype: int64

In [137]:
display(df_pm_cleaned)

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_GEO_CD,BENE_AGE_LVL,BENES_TOTAL_CNT,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_MA_CNT,MA_PRTCPTN_RATE,...,PQI11_BCTRL_PNA_AGE_LT_65,PQI11_BCTRL_PNA_AGE_65_74,PQI11_BCTRL_PNA_AGE_GE_75,PQI12_UTI_AGE_LT_65,PQI12_UTI_AGE_65_74,PQI12_UTI_AGE_GE_75,PQI15_ASTHMA_AGE_LT_40,PQI16_LWRXTRMTY_AMPUTN_AGE_LT_65,PQI16_LWRXTRMTY_AMPUTN_AGE_65_74,PQI16_LWRXTRMTY_AMPUTN_AGE_GE_75
0,2014,National,National,NaN,All,56767775,49302821,33462969,15839852,0.3213,...,686,499,1373,361,269,1120,286,147,50,47
1,2014,National,National,NaN,<65,9286837,7824336,5867170,1957166,0.2501,...,686,NaN,NaN,361,NaN,NaN,286,147,NaN,NaN
2,2014,National,National,NaN,>=65,47480938,41478485,27595799,13882686,0.3347,...,NaN,499,1373,NaN,269,1120,NaN,NaN,50,47
3,2014,State,AK,2.0,All,84573,71860,71383,477,0.0066,...,622,366,1271,181,152,703,<NA>,130,<NA>,72
4,2014,State,AK,2.0,<65,13294,11641,11578,63,0.0054,...,622,NaN,NaN,181,NaN,NaN,<NA>,130,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33634,2023,County,WY-Washakie,56043.0,All,2209,1949,1651,298,0.1529,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33635,2023,County,WY-Weston,56045.0,All,1915,1699,1451,248,0.146,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33636,2023,State,ZZ,NaN,All,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
33637,2023,State,ZZ,NaN,<65,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
33638,2023,State,ZZ,NaN,>=65,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [139]:
columns_to_extract = [
    'YEAR', 'BENE_GEO_DESC', 'BENE_GEO_LVL',
    'TOT_MDCR_STDZD_PYMT_PC', 'TOT_MDCR_PYMT_PC', 
    'IP_MDCR_PYMT_PC','IP_MDCR_STDZD_PYMT_PC',
    'OP_MDCR_PYMT_PC', 'OP_MDCR_STDZD_PYMT_PC',
    'SNF_MDCR_PYMT_PC', 'SNF_MDCR_STDZD_PYMT_PC',
    'HH_MDCR_PYMT_PC', 'HH_MDCR_STDZD_PYMT_PC',
    'HOSPC_MDCR_PYMT_PC', 'HOSPC_MDCR_STDZD_PYMT_PC',
    'EM_MDCR_PYMT_PC', 'EM_MDCR_STDZD_PYMT_PC',
    'FQHC_RHC_MDCR_PYMT_PC', 'FQHC_RHC_MDCR_STDZD_PYMT_PC']

In [141]:
df_pm_trends = df_pm_cleaned[columns_to_extract]

In [143]:
display(df_pm_trends)

,YEAR,BENE_GEO_DESC,BENE_GEO_LVL,TOT_MDCR_STDZD_PYMT_PC,TOT_MDCR_PYMT_PC,IP_MDCR_PYMT_PC,IP_MDCR_STDZD_PYMT_PC,OP_MDCR_PYMT_PC,OP_MDCR_STDZD_PYMT_PC,SNF_MDCR_PYMT_PC,SNF_MDCR_STDZD_PYMT_PC,HH_MDCR_PYMT_PC,HH_MDCR_STDZD_PYMT_PC,HOSPC_MDCR_PYMT_PC,HOSPC_MDCR_STDZD_PYMT_PC,EM_MDCR_PYMT_PC,EM_MDCR_STDZD_PYMT_PC,FQHC_RHC_MDCR_PYMT_PC,FQHC_RHC_MDCR_STDZD_PYMT_PC
0,2014,National,National,9190.6,9767,3241.51,2620.39,1322.45,1298.42,799.41,828.24,494.34,516.33,305.32,311.04,941.49,954.89,38.6,41.88
1,2014,National,National,10078.6,10732.16,4033.33,3285.38,1589.88,1573.62,421.92,435.61,366.12,386.51,92.82,96.64,999.54,1036.5,68.3,73.21
2,2014,National,National,9001.8,9561.79,3073.17,2479.01,1265.59,1239.91,879.67,911.72,521.6,543.94,350.5,356.62,929.14,937.54,32.28,35.22
3,2014,AK,State,6523.5,8602.11,3471.25,2113.82,1660.98,1422.96,348.24,295.78,151.95,133.92,111.77,101.26,683.79,557.49,32.41,30.85
4,2014,AK,State,8173.27,10572.99,4099.61,2582.81,2242.64,1937.32,190.66,167.67,103.65,91.2,37.99,35.03,902.47,733.4,71.85,67.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33634,2023,WY-Washakie,County,11039.24,12266.83,3093.06,2186.3,4388.65,4041.17,1687.26,1759.65,86.72,89.85,161.39,167.09,528.48,534.85,136.15,137.1
33635,2023,WY-Weston,County,9740.89,10787.21,2785.69,2146.95,4158.95,3691.22,1050.23,1098.63,148.4,157.73,<NA>,<NA>,404.8,417.51,168.5,171.96
33636,2023,ZZ,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
33637,2023,ZZ,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
33638,2023,ZZ,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [145]:
df_pm_trends = df_pm_trends[
    ~df_pm_trends['BENE_GEO_DESC'].str.contains("ZZ|UNKNOWN", na=False)]

In [147]:
display(df_pm_trends)

,YEAR,BENE_GEO_DESC,BENE_GEO_LVL,TOT_MDCR_STDZD_PYMT_PC,TOT_MDCR_PYMT_PC,IP_MDCR_PYMT_PC,IP_MDCR_STDZD_PYMT_PC,OP_MDCR_PYMT_PC,OP_MDCR_STDZD_PYMT_PC,SNF_MDCR_PYMT_PC,SNF_MDCR_STDZD_PYMT_PC,HH_MDCR_PYMT_PC,HH_MDCR_STDZD_PYMT_PC,HOSPC_MDCR_PYMT_PC,HOSPC_MDCR_STDZD_PYMT_PC,EM_MDCR_PYMT_PC,EM_MDCR_STDZD_PYMT_PC,FQHC_RHC_MDCR_PYMT_PC,FQHC_RHC_MDCR_STDZD_PYMT_PC
0,2014,National,National,9190.6,9767,3241.51,2620.39,1322.45,1298.42,799.41,828.24,494.34,516.33,305.32,311.04,941.49,954.89,38.6,41.88
1,2014,National,National,10078.6,10732.16,4033.33,3285.38,1589.88,1573.62,421.92,435.61,366.12,386.51,92.82,96.64,999.54,1036.5,68.3,73.21
2,2014,National,National,9001.8,9561.79,3073.17,2479.01,1265.59,1239.91,879.67,911.72,521.6,543.94,350.5,356.62,929.14,937.54,32.28,35.22
3,2014,AK,State,6523.5,8602.11,3471.25,2113.82,1660.98,1422.96,348.24,295.78,151.95,133.92,111.77,101.26,683.79,557.49,32.41,30.85
4,2014,AK,State,8173.27,10572.99,4099.61,2582.81,2242.64,1937.32,190.66,167.67,103.65,91.2,37.99,35.03,902.47,733.4,71.85,67.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33630,2023,WY-Sweetwater,County,8481.66,9652.33,3119.25,2049.06,2163.42,2052.31,673.75,703.45,430.27,448.3,167.11,174.57,612.16,628.7,52.77,54.02
33631,2023,WY-Teton,County,8407.15,9589.83,2747.57,1766.34,2860.56,2695.69,140.15,149.52,171.69,173.94,180.2,186.03,766.78,773.01,20.23,23.03
33633,2023,WY-Uinta,County,9799.05,10542.54,2728.22,1966.79,2643.65,2606.5,461.53,481.85,495.08,519.51,127.41,134.58,644.26,664.66,107.05,108.13
33634,2023,WY-Washakie,County,11039.24,12266.83,3093.06,2186.3,4388.65,4041.17,1687.26,1759.65,86.72,89.85,161.39,167.09,528.48,534.85,136.15,137.1
33635,2023,WY-Weston,County,9740.89,10787.21,2785.69,2146.95,4158.95,3691.22,1050.23,1098.63,148.4,157.73,<NA>,<NA>,404.8,417.51,168.5,171.96

In [149]:
missing_values = df_pm_trends.isna().sum()
missing_values[missing_values > 0]

TOT_MDCR_STDZD_PYMT_PC           40
TOT_MDCR_PYMT_PC                 40
IP_MDCR_PYMT_PC                  94
IP_MDCR_STDZD_PYMT_PC            94
OP_MDCR_PYMT_PC                  49
OP_MDCR_STDZD_PYMT_PC            49
SNF_MDCR_PYMT_PC                768
SNF_MDCR_STDZD_PYMT_PC          768
HH_MDCR_PYMT_PC                1293
HH_MDCR_STDZD_PYMT_PC          1293
HOSPC_MDCR_PYMT_PC             2054
HOSPC_MDCR_STDZD_PYMT_PC       2054
EM_MDCR_PYMT_PC                  47
EM_MDCR_STDZD_PYMT_PC            47
FQHC_RHC_MDCR_PYMT_PC           318
FQHC_RHC_MDCR_STDZD_PYMT_PC     318
dtype: int64

In [151]:
df_missing = df_pm_trends[df_pm_trends.isna().any(axis=1)]

In [153]:
df_missing.shape

(2547, 19)

In [155]:
df_missing.sample(10)

,YEAR,BENE_GEO_DESC,BENE_GEO_LVL,TOT_MDCR_STDZD_PYMT_PC,TOT_MDCR_PYMT_PC,IP_MDCR_PYMT_PC,IP_MDCR_STDZD_PYMT_PC,OP_MDCR_PYMT_PC,OP_MDCR_STDZD_PYMT_PC,SNF_MDCR_PYMT_PC,SNF_MDCR_STDZD_PYMT_PC,HH_MDCR_PYMT_PC,HH_MDCR_STDZD_PYMT_PC,HOSPC_MDCR_PYMT_PC,HOSPC_MDCR_STDZD_PYMT_PC,EM_MDCR_PYMT_PC,EM_MDCR_STDZD_PYMT_PC,FQHC_RHC_MDCR_PYMT_PC,FQHC_RHC_MDCR_STDZD_PYMT_PC
10102,2017,AK-Dillingham,County,8887.95,16941.86,7871.14,2502.71,2881.34,1321.05,<NA>,<NA>,<NA>,<NA>,0,0,609.27,487.67,<NA>,<NA>
25303,2021,MT-Valley,County,9034.27,11138.94,3054.31,1712.16,4625.9,3848.93,1183.06,1269.42,36.13,37.56,<NA>,<NA>,310.32,307.12,731.23,719.45
10104,2017,AK-Haines,County,9057.12,11475.95,3949.02,2329.71,3489.18,3292.65,1150.57,918.68,<NA>,<NA>,<NA>,<NA>,549.16,475.46,16.35,15.33
27234,2022,CO-San Juan,County,5511.41,5918.84,<NA>,<NA>,2030.75,1987.48,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,580.61,595.24,<NA>,<NA>
11821,2017,MT-Liberty,County,9568.94,10685.23,3049.29,2393.36,3268.66,2751.62,1626.96,1711.19,<NA>,<NA>,<NA>,<NA>,408.99,415.35,625.1,627.06
22590,2020,PA-Cameron,County,10852.69,9934.98,2587.98,2409.51,2827.44,3735.87,758.71,879.46,530.23,607.9,<NA>,<NA>,589.92,596.94,470.45,522.29
1977,2014,NE-Keith,County,7234.11,7711.48,2676.72,2227.83,2014.07,1831.2,692.92,752.29,119.25,128.28,<NA>,<NA>,549.56,611.88,20.18,21.38
5125,2015,MT-Wibaux,County,8874.64,9656.97,3512.18,2907.02,2309.18,1961.47,1383.21,1518.76,<NA>,<NA>,<NA>,<NA>,344.56,361.24,232.63,241.08
5115,2015,MT-Sheridan,County,6950.21,7286.54,1680.64,1575.74,2344.19,1958.44,1594.82,1711.75,<NA>,<NA>,<NA>,<NA>,399.66,414.22,196.13,184.09
15329,2018,ND-Burke,County,9492.26,9847.42,2586.13,2119.49,2989.39,2683.9,2547.88,2950.99,<NA>,<NA>,<NA>,<NA>,365.86,386.41,257.84,258.74

In [157]:
df_pm_trends.dtypes

YEAR                            int64
BENE_GEO_DESC                  object
BENE_GEO_LVL                   object
TOT_MDCR_STDZD_PYMT_PC         object
TOT_MDCR_PYMT_PC               object
IP_MDCR_PYMT_PC                object
IP_MDCR_STDZD_PYMT_PC          object
OP_MDCR_PYMT_PC                object
OP_MDCR_STDZD_PYMT_PC          object
SNF_MDCR_PYMT_PC               object
SNF_MDCR_STDZD_PYMT_PC         object
HH_MDCR_PYMT_PC                object
HH_MDCR_STDZD_PYMT_PC          object
HOSPC_MDCR_PYMT_PC             object
HOSPC_MDCR_STDZD_PYMT_PC       object
EM_MDCR_PYMT_PC                object
EM_MDCR_STDZD_PYMT_PC          object
FQHC_RHC_MDCR_PYMT_PC          object
FQHC_RHC_MDCR_STDZD_PYMT_PC    object
dtype: object

In [159]:
payment_cols = df_pm_trends.columns.difference(['YEAR', 'BENE_GEO_DESC', 'BENE_GEO_LVL'])

for col in payment_cols:
    df_pm_trends[col] = pd.to_numeric(df_pm_trends[col], errors='coerce')

In [161]:
df_pm_trends.dtypes

YEAR                             int64
BENE_GEO_DESC                   object
BENE_GEO_LVL                    object
TOT_MDCR_STDZD_PYMT_PC         float64
TOT_MDCR_PYMT_PC               float64
IP_MDCR_PYMT_PC                float64
IP_MDCR_STDZD_PYMT_PC          float64
OP_MDCR_PYMT_PC                float64
OP_MDCR_STDZD_PYMT_PC          float64
SNF_MDCR_PYMT_PC               float64
SNF_MDCR_STDZD_PYMT_PC         float64
HH_MDCR_PYMT_PC                float64
HH_MDCR_STDZD_PYMT_PC          float64
HOSPC_MDCR_PYMT_PC             float64
HOSPC_MDCR_STDZD_PYMT_PC       float64
EM_MDCR_PYMT_PC                float64
EM_MDCR_STDZD_PYMT_PC          float64
FQHC_RHC_MDCR_PYMT_PC          float64
FQHC_RHC_MDCR_STDZD_PYMT_PC    float64
dtype: object

In [163]:
display(df_pm_trends)

,YEAR,BENE_GEO_DESC,BENE_GEO_LVL,TOT_MDCR_STDZD_PYMT_PC,TOT_MDCR_PYMT_PC,IP_MDCR_PYMT_PC,IP_MDCR_STDZD_PYMT_PC,OP_MDCR_PYMT_PC,OP_MDCR_STDZD_PYMT_PC,SNF_MDCR_PYMT_PC,SNF_MDCR_STDZD_PYMT_PC,HH_MDCR_PYMT_PC,HH_MDCR_STDZD_PYMT_PC,HOSPC_MDCR_PYMT_PC,HOSPC_MDCR_STDZD_PYMT_PC,EM_MDCR_PYMT_PC,EM_MDCR_STDZD_PYMT_PC,FQHC_RHC_MDCR_PYMT_PC,FQHC_RHC_MDCR_STDZD_PYMT_PC
0,2014,National,National,9190.60,9767.00,3241.51,2620.39,1322.45,1298.42,799.41,828.24,494.34,516.33,305.32,311.04,941.49,954.89,38.60,41.88
1,2014,National,National,10078.60,10732.16,4033.33,3285.38,1589.88,1573.62,421.92,435.61,366.12,386.51,92.82,96.64,999.54,1036.50,68.30,73.21
2,2014,National,National,9001.80,9561.79,3073.17,2479.01,1265.59,1239.91,879.67,911.72,521.60,543.94,350.50,356.62,929.14,937.54,32.28,35.22
3,2014,AK,State,6523.50,8602.11,3471.25,2113.82,1660.98,1422.96,348.24,295.78,151.95,133.92,111.77,101.26,683.79,557.49,32.41,30.85
4,2014,AK,State,8173.27,10572.99,4099.61,2582.81,2242.64,1937.32,190.66,167.67,103.65,91.20,37.99,35.03,902.47,733.40,71.85,67.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33630,2023,WY-Sweetwater,County,8481.66,9652.33,3119.25,2049.06,2163.42,2052.31,673.75,703.45,430.27,448.30,167.11,174.57,612.16,628.70,52.77,54.02
33631,2023,WY-Teton,County,8407.15,9589.83,2747.57,1766.34,2860.56,2695.69,140.15,149.52,171.69,173.94,180.20,186.03,766.78,773.01,20.23,23.03
33633,2023,WY-Uinta,County,9799.05,10542.54,2728.22,1966.79,2643.65,2606.50,461.53,481.85,495.08,519.51,127.41,134.58,644.26,664.66,107.05,108.13
33634,2023,WY-Washakie,County,11039.24,12266.83,3093.06,2186.30,4388.65,4041.17,1687.26,1759.65,86.72,89.85,161.39,167.09,528.48,534.85,136.15,137.10
33635,2023,WY-Weston,County,9740.89,10787.21,2785.69,2146.95,4158.95,3691.22,1050.23,1098.63,148.40,157.73,NaN,NaN,404.80,417.51,168.50,171.96

In [165]:
df_pm_trends['BENE_GEO_LVL'] = df_pm_trends['BENE_GEO_LVL'].astype(str).str.strip().str.title()

In [167]:
us_state_abbrev = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'FL': 'Florida', 'GA': 'Georgia',
    'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa',
    'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland',
    'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri',
    'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey',
    'NM': 'New Mexico', 'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio',
    'OK': 'Oklahoma', 'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont',
    'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming',
    'DC': 'District of Columbia'
}

In [169]:
df_pm_trends.loc[df_pm_trends['BENE_GEO_LVL'] == 'State', 'BENE_GEO_DESC'] = \
    df_pm_trends.loc[df_pm_trends['BENE_GEO_LVL'] == 'State', 'BENE_GEO_DESC'].map(us_state_abbrev)

In [171]:
display(df_pm_trends)

,YEAR,BENE_GEO_DESC,BENE_GEO_LVL,TOT_MDCR_STDZD_PYMT_PC,TOT_MDCR_PYMT_PC,IP_MDCR_PYMT_PC,IP_MDCR_STDZD_PYMT_PC,OP_MDCR_PYMT_PC,OP_MDCR_STDZD_PYMT_PC,SNF_MDCR_PYMT_PC,SNF_MDCR_STDZD_PYMT_PC,HH_MDCR_PYMT_PC,HH_MDCR_STDZD_PYMT_PC,HOSPC_MDCR_PYMT_PC,HOSPC_MDCR_STDZD_PYMT_PC,EM_MDCR_PYMT_PC,EM_MDCR_STDZD_PYMT_PC,FQHC_RHC_MDCR_PYMT_PC,FQHC_RHC_MDCR_STDZD_PYMT_PC
0,2014,National,National,9190.60,9767.00,3241.51,2620.39,1322.45,1298.42,799.41,828.24,494.34,516.33,305.32,311.04,941.49,954.89,38.60,41.88
1,2014,National,National,10078.60,10732.16,4033.33,3285.38,1589.88,1573.62,421.92,435.61,366.12,386.51,92.82,96.64,999.54,1036.50,68.30,73.21
2,2014,National,National,9001.80,9561.79,3073.17,2479.01,1265.59,1239.91,879.67,911.72,521.60,543.94,350.50,356.62,929.14,937.54,32.28,35.22
3,2014,Alaska,State,6523.50,8602.11,3471.25,2113.82,1660.98,1422.96,348.24,295.78,151.95,133.92,111.77,101.26,683.79,557.49,32.41,30.85
4,2014,Alaska,State,8173.27,10572.99,4099.61,2582.81,2242.64,1937.32,190.66,167.67,103.65,91.20,37.99,35.03,902.47,733.40,71.85,67.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33630,2023,WY-Sweetwater,County,8481.66,9652.33,3119.25,2049.06,2163.42,2052.31,673.75,703.45,430.27,448.30,167.11,174.57,612.16,628.70,52.77,54.02
33631,2023,WY-Teton,County,8407.15,9589.83,2747.57,1766.34,2860.56,2695.69,140.15,149.52,171.69,173.94,180.20,186.03,766.78,773.01,20.23,23.03
33633,2023,WY-Uinta,County,9799.05,10542.54,2728.22,1966.79,2643.65,2606.50,461.53,481.85,495.08,519.51,127.41,134.58,644.26,664.66,107.05,108.13
33634,2023,WY-Washakie,County,11039.24,12266.83,3093.06,2186.30,4388.65,4041.17,1687.26,1759.65,86.72,89.85,161.39,167.09,528.48,534.85,136.15,137.10
33635,2023,WY-Weston,County,9740.89,10787.21,2785.69,2146.95,4158.95,3691.22,1050.23,1098.63,148.40,157.73,NaN,NaN,404.80,417.51,168.50,171.96

In [173]:
df_pm_trends = df_pm_trends.rename(columns={
    'YEAR': 'Year',
    'BENE_GEO_DESC': 'Geo_Entity',
    'BENE_GEO_LVL': 'Geo_Level',

    'TOT_MDCR_PYMT_PC': 'Total Actual Per Capita',
    'TOT_MDCR_STDZD_PYMT_PC': 'Total Standardized Per Capita',

    'IP_MDCR_PYMT_PC': 'IP Actual Per Capita',
    'IP_MDCR_STDZD_PYMT_PC': 'IP Standardized Per Capita',

    'OP_MDCR_PYMT_PC': 'OP Actual Per Capita',
    'OP_MDCR_STDZD_PYMT_PC': 'OP Standardized Per Capita',

    'SNF_MDCR_PYMT_PC': 'SNF Actual Per Capita',
    'SNF_MDCR_STDZD_PYMT_PC': 'SNF Standardized Per Capita',

    'HH_MDCR_PYMT_PC': 'Home Health Actual Per Capita',
    'HH_MDCR_STDZD_PYMT_PC': 'Home Health Standardized Per Capita',

    'HOSPC_MDCR_PYMT_PC': 'Hospice Actual Per Capita',
    'HOSPC_MDCR_STDZD_PYMT_PC': 'Hospice Standardized Per Capita',

    'EM_MDCR_PYMT_PC': 'E&M Actual Per Capita',
    'EM_MDCR_STDZD_PYMT_PC': 'E&M Standardized Per Capita',

    'FQHC_RHC_MDCR_PYMT_PC': 'FQHC Actual Per Capita',
    'FQHC_RHC_MDCR_STDZD_PYMT_PC': 'FQHC Standardized Per Capita'
})

In [175]:
display(df_pm_trends)

,Year,Geo_Entity,Geo_Level,Total Standardized Per Capita,Total Actual Per Capita,IP Actual Per Capita,IP Standardized Per Capita,OP Actual Per Capita,OP Standardized Per Capita,SNF Actual Per Capita,SNF Standardized Per Capita,Home Health Actual Per Capita,Home Health Standardized Per Capita,Hospice Actual Per Capita,Hospice Standardized Per Capita,E&M Actual Per Capita,E&M Standardized Per Capita,FQHC Actual Per Capita,FQHC Standardized Per Capita
0,2014,National,National,9190.60,9767.00,3241.51,2620.39,1322.45,1298.42,799.41,828.24,494.34,516.33,305.32,311.04,941.49,954.89,38.60,41.88
1,2014,National,National,10078.60,10732.16,4033.33,3285.38,1589.88,1573.62,421.92,435.61,366.12,386.51,92.82,96.64,999.54,1036.50,68.30,73.21
2,2014,National,National,9001.80,9561.79,3073.17,2479.01,1265.59,1239.91,879.67,911.72,521.60,543.94,350.50,356.62,929.14,937.54,32.28,35.22
3,2014,Alaska,State,6523.50,8602.11,3471.25,2113.82,1660.98,1422.96,348.24,295.78,151.95,133.92,111.77,101.26,683.79,557.49,32.41,30.85
4,2014,Alaska,State,8173.27,10572.99,4099.61,2582.81,2242.64,1937.32,190.66,167.67,103.65,91.20,37.99,35.03,902.47,733.40,71.85,67.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33630,2023,WY-Sweetwater,County,8481.66,9652.33,3119.25,2049.06,2163.42,2052.31,673.75,703.45,430.27,448.30,167.11,174.57,612.16,628.70,52.77,54.02
33631,2023,WY-Teton,County,8407.15,9589.83,2747.57,1766.34,2860.56,2695.69,140.15,149.52,171.69,173.94,180.20,186.03,766.78,773.01,20.23,23.03
33633,2023,WY-Uinta,County,9799.05,10542.54,2728.22,1966.79,2643.65,2606.50,461.53,481.85,495.08,519.51,127.41,134.58,644.26,664.66,107.05,108.13
33634,2023,WY-Washakie,County,11039.24,12266.83,3093.06,2186.30,4388.65,4041.17,1687.26,1759.65,86.72,89.85,161.39,167.09,528.48,534.85,136.15,137.10
33635,2023,WY-Weston,County,9740.89,10787.21,2785.69,2146.95,4158.95,3691.22,1050.23,1098.63,148.40,157.73,NaN,NaN,404.80,417.51,168.50,171.96

In [177]:
df_pm_trends.to_csv("medicare_payment_models.csv", index=False)